### ISSUE TITLE
ObjRelease() missing param in ahk2.d.ahk

### ISSUE THREAD

**Issue by camkidd** [GroggyOtter/ahkv2_definition_rewrite#1]
ObjRelease is missing the Ptr param, so erroneously flags problem as "Expected 0 paramater, but got 1"
Should be `ObjRelease(Ptr) => Integer`
https://github.com/GroggyOtter/ahkv2_definition_rewrite/blob/c5c1c8fe1a9d88fe86d62b31349390404863ab17/ahk2.d.ahk#L18820

So small I figure it's easier for you to fix than create a pull request. Hope that's ok.

**Comment by GroggyOtter** [comment]
Fixed.  
Thanks for taking the time to report it.
