### ISSUE TITLE
AutoHotkey2 server crashed

### ISSUE THREAD

**Issue by AndyZaa** [GroggyOtter/ahkv2_definition_rewrite#2]
Hi @GroggyOtter,
Looks like a great utility! I just started out with AutoHotkey. I had Visual Studio Code installed already for some time, and it is fully up to date. Today I installed THQBY's AHKv2 support addon and that worked fine. 

When I install your two files, I get the errors shown below. I've gone back and forth between your files and the original THQBY's AHKv2 support addon files, with rebooting my computer. The THQBY's AHKv2 support addon files operate without error, but when I use yours I get the same errors every time.

![image](https://github.com/GroggyOtter/ahkv2_definition_rewrite/assets/55149357/45ed2bd6-f83c-42fd-af45-06d25c47a89f)

Any idea on what I could be doing wrong, or how I can more effectively troubleshoot? Thank you!

**Comment by GroggyOtter** [comment]
I just now copied and pasted the currently posted definition files into the current v2 addon and I cannot duplicate the problem.

Ensure you're using an up-to-date version of THQBY's addon. His addon is currently version 2.3.2.  
You can also try removing all previous versions that are found in the extensions folder. They should start with `thqby.vscode-autohotkey2-lsp-<VERSION_NUMBER>`.

Furthermore, I have no idea why the definition file would possibly cause an error in the server startup of the addon.
The error looks like it's attempting to parse some HTML file as JSON, which would obviously produce an error.
Neither of my files have HTML in them, so I'm not sure what the origin of the error is.

Worst case scenario, I'd do a fresh install of VS Code and THQBY's addon. Then apply the updated definition files.

**Comment by AndyZaa** [comment]
Thanks @GroggyOtter. I did a fresh install of all, and now I'm fine. I'm guessing operator error on my part. I've used your code addition a bunch over the last couple of days - it is superb. Thanks again!

**Comment by GroggyOtter** [comment]
I'm really glad to hear you got it working.
BTW, keep an eye on the GitHub page. I'm working on a massive update that fixes a ton of typos/errors, adds more information, restructures many things, and incorporates a good chunk of the missing example code.

It's really nice to know that there are some people actually using this.  
Thx for reaching out.
