### ISSUE TITLE
Let's work to get this into AHK++

### ISSUE THREAD

**Issue by mark-wiemer** [GroggyOtter/ahkv2_definition_rewrite#8]
Hey @GroggyOtter, I feel like we've met before, or maybe I just saw your posts on the forums. Anyway, this project looks awesome, and I've opened an issue in AHK++ to get this implemented. Feel free to open a PR, otherwise I'll come to this once I've added some more unit tests!

**Comment by GroggyOtter** [comment]
As long as the addon parses JSDoc comments, the definition file should mostly work, minus some formatting that's unique to THQBY's addon.  
The JSON file most likely won't work as it's specific to the addon.  

If you want to convert it for use with another addon, feel free. All I ask is credit me in the file as the creator of it. 👍

**Comment by mark-wiemer** [comment]
Yes, you'll be 100% credited of course :) I'm working on fixing two other bugs now, but progress is good and adding this file will be next. I'll keep you posted if I have questions :)
