### ISSUE TITLE
Keywords to add

### ISSUE THREAD

**Issue by wilkster** [GroggyOtter/ahkv2_definition_rewrite#9]
I am getting the following problems identified. The last is unique to V2 Alpha 9+ but the first should be handled
![image](https://github.com/user-attachments/assets/707fd1bc-70a2-445b-b9a6-f3295504a235)

Also, works fine by putting the two files into their own location and changing the VS Code extension
![image](https://github.com/user-attachments/assets/f22dcab5-63e4-4df9-ac13-547ccf505ca5)

**Comment by GroggyOtter** [comment]
StructFromPtr is a v2.1 thing.
v2.1 isn't supported as it's still in Alpha.  
I won't be updating this definition file until 2.1 stable is released.
